-- MediBook: doctors and appointments schema

-- Standard updated_at trigger function
create or replace function public.handle_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Doctors
create table public.doctors (
  id bigint generated by default as identity primary key,
  name text not null,
  specialty text not null,
  avatar text not null,
  rating numeric(2, 1) not null check (rating >= 0 and rating <= 5),
  reviews integer not null check (reviews >= 0),
  experience integer not null check (experience >= 0),
  city text not null,
  price numeric(10, 2) not null check (price >= 0),
  available boolean not null default true,
  languages text not null,
  insurance text not null,
  about text not null,
  address text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger doctors_updated_at
  before update on public.doctors
  for each row
  execute function public.handle_updated_at();

-- Appointments
create table public.appointments (
  id bigint generated by default as identity primary key,
  doctor_id bigint not null references public.doctors (id) on delete restrict,
  patient_id uuid not null references auth.users (id) on delete cascade,
  date date not null,
  time text not null,
  location text not null,
  total numeric(10, 2) not null check (total >= 0),
  status text not null default 'upcoming'
    check (status in ('upcoming', 'past', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger appointments_updated_at
  before update on public.appointments
  for each row
  execute function public.handle_updated_at();

-- Prevent double-booking for active appointments (cancelled slots can be rebooked)
create unique index appointments_doctor_date_time_active_idx
  on public.appointments (doctor_id, date, time)
  where status <> 'cancelled';

create index appointments_patient_id_idx on public.appointments (patient_id);
create index appointments_doctor_id_idx on public.appointments (doctor_id);

-- Row Level Security
alter table public.doctors enable row level security;
alter table public.appointments enable row level security;

-- Doctors: public read, no client-side writes
create policy "Doctors are viewable by everyone"
  on public.doctors
  for select
  to anon, authenticated
  using (true);

-- Appointments: authenticated users only
create policy "Users can view their own appointments"
  on public.appointments
  for select
  to authenticated
  using (patient_id = (select auth.uid()));

create policy "Users can create their own appointments"
  on public.appointments
  for insert
  to authenticated
  with check (patient_id = (select auth.uid()));

create policy "Users can update their own appointments"
  on public.appointments
  for update
  to authenticated
  using (patient_id = (select auth.uid()))
  with check (patient_id = (select auth.uid()));

-- Grants
grant usage on schema public to anon, authenticated;

grant select on public.doctors to anon, authenticated;

grant select, insert, update on public.appointments to authenticated;

grant usage, select on all sequences in schema public to authenticated;
